build: false

skip_branch_with_pr: true

image:
  - macOS
  - Ubuntu
  - Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "Current"

configuration: Release
platform:
  - x86
  - x64

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - cmd: npm run prebuild
  - sh: npm run prebuild

matrix:
  fast_finish: true

deploy:
  - provider: GitHub
    artifact: /.*(\.zip|\.tar)/
    draft: false
    prerelease: true
    auth_token:
      secure: lgmuC+ZF5mypnRDBWnIJ5WOIe2EvkXIrh4bxYDp7E6or46yqXQUBW+4VVu4ru5bG
    on:
      APPVEYOR_REPO_TAG: true
      nodejs_version: "Current"

# filter the above matrix by image, apply config to matches
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
    install:
      - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
      - ps: Install-Product node $env:nodejs_version $env:platform
      - npm install
    artifacts:
      - path: prebuilds
        name: $(APPVEYOR_REPO_TAG_NAME)-win-$(PLATFORM)
        type: zip
  -
    matrix:
      only:
        - image: Ubuntu
    install:
      - sh: sudo apt-get install -y libasound2-dev
      - sh: nvm install --lts
      - npm install
    artifacts:
      - path: prebuilds
        name: $(APPVEYOR_REPO_TAG_NAME)-linux-$(PLATFORM)
        type: tar
  -
    matrix:
      only:
        - image: macOS
    install:
      - sh: nvm install --lts
      - npm install
    artifacts:
      - path: prebuilds
        name: $(APPVEYOR_REPO_TAG_NAME)-darwin-$(PLATFORM)
        type: tar